// Generated by CoffeeScript 1.6.2
(function() {
  var launch_popout, launch_unique_popout, name, popouts, videos;

  popouts = [];

  videos = [];

  name = function(request) {
    return "Popout_for_YouTube_" + request.title;
  };

  launch_popout = function(request, sender) {
    var window;

    return window = chrome.windows.create({
      type: 'popup',
      url: 'popout.html',
      width: request.width,
      height: request.height
    }, function(window) {
      popouts[name(request)] = window.id;
      request.name = name(request);
      request.original_tab_id = sender.tab.id;
      return videos[window.tabs[0].id] = request;
    });
  };

  launch_unique_popout = function(request, sender) {
    if (popouts[name(request)]) {
      try {
        return chrome.windows.remove(popouts[name(request)], function() {
          return launch_popout(request, sender);
        });
      } catch (_error) {}
    } else {
      return launch_popout(request, sender);
    }
  };

  chrome.extension.onRequest.addListener(function(request, sender, send_response) {
    if (request.action === 'launch') {
      launch_unique_popout(request, sender);
    }
    if (request.action === 'current_time') {
      chrome.tabs.sendRequest(request.original_tab_id, {
        action: 'current_time',
        current_time: request.current_time
      });
    }
    if (request.action === 'get_video') {
      return send_response(videos[sender.tab.id]);
    }
  });

}).call(this);
