// Generated by CoffeeScript 1.6.2
/*
Author: Justin Force <justin.force@gmail.com
Copyright 2012 by Justin Force
GitHub: http://github.com/sidewaysmilk/popout_for_youtube
License: 3-clause BSD license
         http://www.w3.org/Consortium/Legal/2008/03-bsd-license.html
*/


(function() {
  var $player, BODY, FLASH, HTML5, PLAY_PAUSE, VIDEO, WINDOW, attach_button, bind_events, button, current_time, get_current_time, launch_popout, play_video, player, player_type, position_button, resume, seek, set_button_bottom_left_corner_to, set_player_and_type, src, stop_video, stopped, video_id, video_top_right_corner;

  WINDOW = $(window);

  BODY = $('body');

  VIDEO = 'video, embed';

  PLAY_PAUSE = '[data-default-title=Play]';

  HTML5 = false;

  FLASH = false;

  button = $('<button id=popout_for_youtube>Pop out');

  player = null;

  $player = null;

  player_type = null;

  current_time = null;

  stopped = false;

  src = null;

  video_id = function() {
    var id;

    id = null;
    try {
      id = $('link[rel=canonical]').attr('href').match(/v=([^&]+)/)[1];
    } catch (_error) {}
    try {
      if (!id) {
        id = $('script').text().match(/"video_id": "([^"]+)"/)[1];
      }
    } catch (_error) {}
    try {
      if (!id) {
        id = location.href.match(/v=([^&]+)/)[1];
      }
    } catch (_error) {}
    return id;
  };

  get_current_time = function() {
    if (FLASH) {
      current_time = player.getCurrentTime();
    }
    if (HTML5) {
      return current_time = player.currentTime;
    }
  };

  seek = function() {
    if (FLASH) {
      player.seekTo(current_time - 1);
    }
    if (HTML5) {
      return player.currentTime = current_time - 1;
    }
  };

  resume = function(e) {
    $(player).add($(PLAY_PAUSE)).unbind('click.resume', resume);
    player.src = src;
    return player.load();
  };

  stop_video = function() {
    if (FLASH) {
      player.stopVideo();
    }
    if (HTML5) {
      player.pause();
      if (!src) {
        src = player.src;
      }
      player.src = '';
      player.load();
      stopped = true;
      $(player).bind('canplaythrough', function(e) {
        $(player).unbind(e);
        seek();
        return player.play();
      });
      return $(player).add($(PLAY_PAUSE)).bind('click.resume', resume);
    }
  };

  play_video = function() {
    seek();
    if (FLASH) {
      player.playVideo();
    }
    if (HTML5) {
      player.src = src;
      player.load();
      return player.play();
    }
  };

  launch_popout = function() {
    return chrome.extension.sendRequest({
      width: $(player).outerWidth(true),
      height: $(player).outerHeight(true),
      action: 'launch',
      video_id: video_id(),
      title: document.title,
      current_time: current_time
    });
  };

  position_button = function() {
    return set_button_bottom_left_corner_to(video_top_right_corner());
  };

  set_button_bottom_left_corner_to = function(location) {
    return button.css({
      left: location.x,
      top: location.y - button.height()
    });
  };

  video_top_right_corner = function() {
    return {
      x: $player.width() + $player.offset().left,
      y: $player.offset().top
    };
  };

  attach_button = function() {
    $(BODY).append(button);
    return setInterval(position_button, 100);
  };

  bind_events = function() {
    button.mousedown(function() {
      return button.css({
        marginTop: 1
      });
    });
    button.mouseup(function() {
      return button.css({
        marginTop: 0
      });
    });
    return button.click(function() {
      get_current_time();
      stop_video();
      return launch_popout();
    });
  };

  set_player_and_type = function(callback) {
    var clear_and_callback, interval, video_node;

    interval = null;
    video_node = null;
    clear_and_callback = function() {
      clearInterval(interval);
      player = video_node;
      $player = $(player);
      try {
        player.play();
      } catch (_error) {}
      return callback();
    };
    return interval = setInterval(function() {
      video_node = $(VIDEO).get(0);
      $('#branded-page-body .html5-video-loader').click();
      if (video_node !== void 0) {
        if (video_node.nodeName === 'VIDEO') {
          HTML5 = true;
          return clear_and_callback();
        } else if (video_node.nodeName === 'EMBED') {
          FLASH = true;
          return clear_and_callback();
        }
      }
    }, 100);
  };

  chrome.extension.onRequest.addListener(function(request, sender, send_response) {
    if (request.action === 'current_time') {
      return current_time = request.current_time;
    }
  });

  $(function() {
    return set_player_and_type(function() {
      attach_button();
      return bind_events();
    });
  });

}).call(this);
